
  CREATE TABLE "SRC"."IPL_MAIN" 
   (	"ID" NUMBER(7,0), 
	"INNINGS" NUMBER(2,0), 
	"OVERS" NUMBER(2,0), 
	"BALLNUMBER" NUMBER(2,0), 
	"BATTER" VARCHAR2(13 BYTE), 
	"BOWLER" VARCHAR2(17 BYTE), 
	"NON_STRIKER" VARCHAR2(17 BYTE), 
	"EXTRA_TYPE" VARCHAR2(7 BYTE), 
	"BATSMAN_RUN" NUMBER(2,0), 
	"EXTRAS_RUN" NUMBER(2,0), 
	"TOTAL_RUN" NUMBER(2,0), 
	"NON_BOUNDARY" NUMBER(2,0), 
	"ISWICKETDELIVERY" NUMBER(2,0), 
	"PLAYER_OUT" VARCHAR2(12 BYTE), 
	"KIND" VARCHAR2(17 BYTE), 
	"FIELDERS_INVOLVED" VARCHAR2(14 BYTE), 
	"BATTINGTEAM" VARCHAR2(27 BYTE), 
	"CITY" VARCHAR2(13 BYTE), 
	"DATE_M" VARCHAR2(19 BYTE), 
	"SEASON" VARCHAR2(7 BYTE), 
	"MATCHNUMBER" VARCHAR2(17 BYTE), 
	"TEAM1" VARCHAR2(27 BYTE), 
	"TM1" VARCHAR2(27 BYTE), 
	"TEAM2" VARCHAR2(27 BYTE), 
	"TM2" VARCHAR2(27 BYTE), 
	"VENUE" VARCHAR2(52 BYTE), 
	"TOSSWINNER" VARCHAR2(27 BYTE), 
	"TOSSDECISION" VARCHAR2(5 BYTE), 
	"SUPEROVER" VARCHAR2(2 BYTE), 
	"WINNINGTEAM" VARCHAR2(27 BYTE), 
	"WONBY" VARCHAR2(9 BYTE), 
	"MARGIN" VARCHAR2(3 BYTE), 
	"METHOD" VARCHAR2(3 BYTE), 
	"PLAYER_OF_MATCH" VARCHAR2(17 BYTE), 
	"TEAM1PLAYERS" VARCHAR2(170 BYTE), 
	"TEAM2PLAYERS" VARCHAR2(174 BYTE), 
	"UMPIRE1" VARCHAR2(21 BYTE), 
	"UMPIRE2" VARCHAR2(21 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

